# -*- coding: utf-8 -*-
"""Web Analyitics - Paper 3 - Final Try.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AgfrW0B0znhGGC1inD6_n0Ew-p26rPQm
"""

#Δημιουργία πίνακα από Homework 1 & 2
from bs4 import BeautifulSoup
import time
import requests
import csv
import os

url_list = [
    'https://www.airlinequality.com/airline-reviews/aegean-airlines',
    'https://www.airlinequality.com/airline-reviews/british-airways',
    'https://www.airlinequality.com/airline-reviews/emirates',
    'https://www.airlinequality.com/airline-reviews/lufthansa',
    'https://www.airlinequality.com/airline-reviews/ryanair',
    'https://www.airlinequality.com/airline-reviews/air-canada-rouge',
    'https://www.airlinequality.com/airline-reviews/turkish-airlines',
    'https://www.airlinequality.com/airline-reviews/easyjet',
]

def get_reviews(base_url, writer):
    page = 1

    while page <= 10:

        if page == 1:
            url = base_url
        else:
            url = f"{base_url}/page/{page}/"

        print(f"Scraping {url} ...")

        response = None
        for i in range(3):
            try:
                response = requests.get(url, headers={'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'})
                if response.status_code == 200:
                    break
                else:
                    time.sleep(2)
            except:
                time.sleep(2)

        if not response or response.status_code != 200:
            break

        soup = BeautifulSoup(response.text, 'html.parser')
        reviews = soup.findAll('article', {'itemprop':'review'})

        if len(reviews) == 0:
            break

        print(f"Found {len(reviews)} reviews on page {page}")

        for review in reviews:
            text = 'NA'
            rating = 'NA

            #text
            textBox = review.find('div', {'class':'text_content'})
            if textBox:
                text_content = textBox.text.strip()
                if '|' in text_content:
                    text_content = text_content.split('|')[1].strip()
                text = text_content

            # ratings
            ratingBox = review.find('span', {'itemprop':'ratingValue'})
            if ratingBox:
                rating = ratingBox.text.strip()

            if text != 'NA' and rating != 'NA':
                writer.writerow([text, rating])

        page += 1
        time.sleep(1)

outpath = 'reviews.csv'

with open(outpath, 'w', encoding='utf8', newline='') as fw:
    writer = csv.writer(fw)
    writer.writerow(['text', 'rating'])

    for url in url_list:
        get_reviews(url, writer)

print("Done")

#Predictive Modeling
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics import classification_report

df = pd.read_csv('reviews.csv')

print(f"Σύνολο κριτικών: {len(df)}")
print(df.head())

df['rating'] = pd.to_numeric(df['rating'], errors='coerce')

df = df.dropna(subset=['rating', 'text'])

df['sentiment'] = df['rating'].apply(lambda x: 1 if x > 5 else 0)

print("\nΚατανομή συναισθήματος (0=Negative, 1=Positive):")
print(df['sentiment'].value_counts())

X_text = df['text']
y = df['sentiment']

vectorizer = CountVectorizer(stop_words='english', max_features=2000)
X = vectorizer.fit_transform(X_text)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

print(f"\nTraining set size: {X_train.shape[0]}")
print(f"Test set size: {X_test.shape[0]}")

#Decision Tree
from sklearn.tree import DecisionTreeClassifier
#Naive Bayes
from sklearn.naive_bayes import MultinomialNB

models_config = [
    {
        #Decision Tree
        "name": "Decision Tree",
        "model": DecisionTreeClassifier(),
        "params": {
            "max_depth": [5, 10, 20],
            "min_samples_split": [2, 10]
        }
    },
    {
        #Naive Bayes
        "name": "Naive Bayes",
        "model": MultinomialNB(),
        "params": {
            "alpha": [0.1, 1.0],
            "fit_prior": [True, False]
        }
    },
]

for config in models_config:
    print(f"\n{'='*40}")
    print(f"Training Model: {config['name']}...")

    grid = GridSearchCV(
        estimator=config['model'],
        param_grid=config['params'],
        cv=3,
        n_jobs=-1,
        verbose=1
    )


    grid.fit(X_train, y_train)

    best_model = grid.best_estimator_
    print(f"Best Params: {grid.best_params_}")
    print(f"Best CV Score: {grid.best_score_:.4f}")

    y_pred = best_model.predict(X_test)

    print(f"\nClassification Report for {config['name']}:")
    print(classification_report(y_test, y_pred))